# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from plumbrc.proto import plumbr_pb2 as plumbr__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plumbr_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PlumbrServiceStub(object):
    """PlumbrC Redaction Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Redact = channel.unary_unary(
                '/plumbr.v1.PlumbrService/Redact',
                request_serializer=plumbr__pb2.RedactRequest.SerializeToString,
                response_deserializer=plumbr__pb2.RedactResponse.FromString,
                _registered_method=True)
        self.RedactBatch = channel.unary_unary(
                '/plumbr.v1.PlumbrService/RedactBatch',
                request_serializer=plumbr__pb2.RedactBatchRequest.SerializeToString,
                response_deserializer=plumbr__pb2.RedactBatchResponse.FromString,
                _registered_method=True)
        self.RedactStream = channel.stream_stream(
                '/plumbr.v1.PlumbrService/RedactStream',
                request_serializer=plumbr__pb2.RedactRequest.SerializeToString,
                response_deserializer=plumbr__pb2.RedactResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/plumbr.v1.PlumbrService/Health',
                request_serializer=plumbr__pb2.HealthRequest.SerializeToString,
                response_deserializer=plumbr__pb2.HealthResponse.FromString,
                _registered_method=True)


class PlumbrServiceServicer(object):
    """PlumbrC Redaction Service
    """

    def Redact(self, request, context):
        """Single line redaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RedactBatch(self, request, context):
        """Batch redaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RedactStream(self, request_iterator, context):
        """Bidirectional streaming — maximum throughput
        Client streams lines in, server streams redacted lines back
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PlumbrServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Redact': grpc.unary_unary_rpc_method_handler(
                    servicer.Redact,
                    request_deserializer=plumbr__pb2.RedactRequest.FromString,
                    response_serializer=plumbr__pb2.RedactResponse.SerializeToString,
            ),
            'RedactBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.RedactBatch,
                    request_deserializer=plumbr__pb2.RedactBatchRequest.FromString,
                    response_serializer=plumbr__pb2.RedactBatchResponse.SerializeToString,
            ),
            'RedactStream': grpc.stream_stream_rpc_method_handler(
                    servicer.RedactStream,
                    request_deserializer=plumbr__pb2.RedactRequest.FromString,
                    response_serializer=plumbr__pb2.RedactResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=plumbr__pb2.HealthRequest.FromString,
                    response_serializer=plumbr__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plumbr.v1.PlumbrService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('plumbr.v1.PlumbrService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PlumbrService(object):
    """PlumbrC Redaction Service
    """

    @staticmethod
    def Redact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plumbr.v1.PlumbrService/Redact',
            plumbr__pb2.RedactRequest.SerializeToString,
            plumbr__pb2.RedactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RedactBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plumbr.v1.PlumbrService/RedactBatch',
            plumbr__pb2.RedactBatchRequest.SerializeToString,
            plumbr__pb2.RedactBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RedactStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/plumbr.v1.PlumbrService/RedactStream',
            plumbr__pb2.RedactRequest.SerializeToString,
            plumbr__pb2.RedactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plumbr.v1.PlumbrService/Health',
            plumbr__pb2.HealthRequest.SerializeToString,
            plumbr__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
