# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plumbr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'plumbr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cplumbr.proto\x12\tplumbr.v1\"\x1d\n\rRedactRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"X\n\x0eRedactResponse\x12\x10\n\x08redacted\x18\x01 \x01(\t\x12\x18\n\x10patterns_matched\x18\x02 \x01(\x05\x12\x1a\n\x12processing_time_ms\x18\x03 \x01(\x01\"#\n\x12RedactBatchRequest\x12\r\n\x05texts\x18\x01 \x03(\t\"\x8a\x01\n\x13RedactBatchResponse\x12*\n\x07results\x18\x01 \x03(\x0b\x32\x19.plumbr.v1.RedactResponse\x12\x13\n\x0btotal_lines\x18\x02 \x01(\x05\x12\x16\n\x0etotal_modified\x18\x03 \x01(\x05\x12\x1a\n\x12processing_time_ms\x18\x04 \x01(\x01\"\x0f\n\rHealthRequest\"b\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x17\n\x0fpatterns_loaded\x18\x03 \x01(\x03\x12\x16\n\x0euptime_seconds\x18\x04 \x01(\x01\x32\xa4\x02\n\rPlumbrService\x12=\n\x06Redact\x12\x18.plumbr.v1.RedactRequest\x1a\x19.plumbr.v1.RedactResponse\x12L\n\x0bRedactBatch\x12\x1d.plumbr.v1.RedactBatchRequest\x1a\x1e.plumbr.v1.RedactBatchResponse\x12G\n\x0cRedactStream\x12\x18.plumbr.v1.RedactRequest\x1a\x19.plumbr.v1.RedactResponse(\x01\x30\x01\x12=\n\x06Health\x12\x18.plumbr.v1.HealthRequest\x1a\x19.plumbr.v1.HealthResponseB\'Z%github.com/AmritRai1234/plumbrC/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plumbr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z%github.com/AmritRai1234/plumbrC/proto'
  _globals['_REDACTREQUEST']._serialized_start=27
  _globals['_REDACTREQUEST']._serialized_end=56
  _globals['_REDACTRESPONSE']._serialized_start=58
  _globals['_REDACTRESPONSE']._serialized_end=146
  _globals['_REDACTBATCHREQUEST']._serialized_start=148
  _globals['_REDACTBATCHREQUEST']._serialized_end=183
  _globals['_REDACTBATCHRESPONSE']._serialized_start=186
  _globals['_REDACTBATCHRESPONSE']._serialized_end=324
  _globals['_HEALTHREQUEST']._serialized_start=326
  _globals['_HEALTHREQUEST']._serialized_end=341
  _globals['_HEALTHRESPONSE']._serialized_start=343
  _globals['_HEALTHRESPONSE']._serialized_end=441
  _globals['_PLUMBRSERVICE']._serialized_start=444
  _globals['_PLUMBRSERVICE']._serialized_end=736
# @@protoc_insertion_point(module_scope)
